options:
  interface-bridge-mappings:
    type: string
    default:
    description: >
      A space-delimited list of key-value pairs that map a network interface
      MAC address or name to a local ovs bridge to which it should be
      connected.

      Note: MAC addresses of physical interfaces that belong to a bond will be
      resolved to the bond name and the bond will be added to the ovs bridge.

      Bridges referenced here must be mentioned in the `ovn-bridge-mappings`
      configuration option.

      If a match is found the bridge will be created if it does not already
      exist, the matched interface will be added to it and the mapping found in
      `ovn-bridge-mappings` will be added to the local OVSDB under the
      `external_ids:ovn-bridge-mappings` key in the Open_vSwitch table.

      An example value mapping two network interface mac address to two ovs
      bridges would be:

          00:00:5e:00:00:42:br-internet enp3s0f0:br-provider


      Note: OVN gives you distributed East/West and highly available
      North/South routing by default.  You do not need to add provider networks
      for use with external Layer3 connectivity to all chassis.

      Doing so will create a scaling problem at the physical network layer
      that needs to be resolved with globally shared Layer2 (does not scale) or
      tunneling at the top-of-rack switch layer (adds complexity) and is
      generally not a recommended configuration.

      Add provider networks for use with external Layer3 connectivity to
      individual chassis located near the datacenter border gateways by adding
      the MAC address of the physical interfaces of those units.
  ovn-bridge-mappings:
    type: string
    default:
    description: >
      A space-delimited list of key-value pairs that map a physical network
      name to a local ovs bridge that provides connectivity to that network.

      The physical network name can be referenced when the administrator
      programs the OVN logical flows either by talking directly to the
      Northbound database or by interfacing with a Cloud Management System
      (CMS).

      Each charm unit will evaluate each key-value pair and determine if the
      configuration is relevant for the host it is running on based on matches
      found in the `interface-bridge-mappings` configuration option.

      If a match is found the bridge will be created if it does not already
      exist, the matched interface will be added to it and the mapping will be
      added to the local OVSDB under the `external_ids:ovn-bridge-mappings` key
      in the Open_vSwitch table.

      An example value mapping two physical network names to two ovs bridges
      would be:

          physnet1:br-internet physnet2:br-provider

      NOTE: Values in this configuration option will only have effect for units
      that have a interface referenced in the `interface-bridge-mappings`
      configuration option.
